version: '3.9'

services:
  mydjango:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8080:8000
    depends_on:
      - mypostgres
      - minio
    volumes:
      - .:/app
  mypostgres:
    image: postgres:11.18-alpine
    environment:
 #    MYSQL_ROOT_PASSWORD: rootpassword
      POSTGRES_DB: djangoapp
      POSTGRES_USER: remote_user
      POSTGRES_PASSWORD: 123456
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password