# Generated by Django 4.1.2 on 2022-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Correo',
            field=models.CharField(default='hola', max_length=50, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
